image: alpine:latest

variables:
  # CInkstone
  SERVICE:            cinkstone-proto

stages:
  - test
  - deploy

# TEST-----------------------------------------------------------------------

.essential:
  before_script:
    - apt-get update && apt-get install -y build-essential unzip
    # Install NPM
    - curl -sL https://deb.nodesource.com/setup_11.x | bash -
    - apt-get install -y nodejs

code_quality:
  extends:       .essential
  stage:         test
  allow_failure: true
  image:
    name: golang:1.11.1
  script:
    # LINT
    - make install
    - make lint 2>&1 | tee lint.log
  artifacts:
    name: "$CI_JOB_STAGE-$CI_JOB_NAME-$CI_COMMIT_SHA"
    paths:
      - lint.log
    when: on_failure
  only:
    - branches
  except:
    variables:
      - $CODE_QUALITY_DISABLED

protolock:
  extends:       .essential
  stage:         test
  allow_failure: true
  image:
    name: golang:1.11.1
  script:
    # PROTOLOCK
    - make install
    - make lock 2>&1 | tee lock.log
  artifacts:
    name: "$CI_JOB_STAGE-$CI_JOB_NAME-$CI_COMMIT_SHA"
    paths:
      - lock.log
    when: on_failure
  only:
    - branches
  except:
    variables:
      - $CODE_QUALITY_DISABLED

pages:
  extends:       .essential
  stage:         deploy
  allow_failure: true
  image:
    name: golang:1.11.1
  script:
    # DOC
    - make install
    - make doc
    - cp -n public/proto.html public/index.html
  artifacts:
    name: "$CI_JOB_STAGE-$CI_JOB_NAME-$CI_COMMIT_SHA"
    paths:
      - public
    when: on_success
  only:
    - branches
  except:
    variables:
      - $GITLAB_PAGES_DISABLED