name: Test

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    container:
      image: golang:1.13.3-alpine
    steps:
      - run: |
              apk add --update make
              make install-prototool

