name: Test

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    container:
      image: docker://golang:1.13.3-alpine
    steps:
      - run: |
              echo Add other actions to build,
              echo test, and deploy your project.
