name: Test

on: [push]

jobs:
  lint:
    name:    Lint
    runs-on: ubuntu-18.04
    container:
      image: golang:1.13.3-alpine
    steps:
      - name:              Install
        uses:              actions/checkout@v1
        working-directory: $GITHUB_WORKSPACE
        run:               |
                           apk add --update make
                           pwd
                           make install-prototool

