name: Test

on: [push]

jobs:
  lint:
    name:    Lint
    runs-on: ubuntu-18.04
    container:
      image: golang:1.13.3-alpine
    steps:
      - name:              Checkout
        uses:              actions/checkout@v1
      - name:              Install
        run:               |
                           apk add --update make git
                           git describe --tags
                           pwd
                           make install-prototool
                           prototool version

